version: '3'

services:
  sodawebfront:
    image: soda-node-pnpm:latest
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 4000:3000
      - 4001:3001
    environment:
      - API_URL=https://pro-api.dev-2.priros.com
      - AES_SECRET_KEY=22ea0aeac00792392c73b53ea359abf2
    expose:
      - 4000
      - 4001
    networks:
      priros_local_network:
    command: ['sh', '-c', 'pnpm dev']
networks:
  priros_local_network:
    external: true
